export const revalidate = 86400; // 24h ISR cache
import { getCityBySlug, CITIES } from "@/lib/db";
import { THERMO_TAILLES, getThermoTailleBySlug } from "@/data/thermo-tailles";
import { notFound } from "next/navigation"; import type { Metadata } from "next";
import ThermoContentPage from "@/components/ThermoContentPage";
type Params = Promise<{ slug: string }>;
export async function generateStaticParams() { return THERMO_TAILLES.map((t) => ({ slug: t.slug })); }
const BASE = "https://www.thermostatcopropriete.fr";
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const { slug } = await params; const t = getThermoTailleBySlug(slug); if (!t) return {}; const url = `${BASE}/taille/${slug}`; return { title: `${t.taille} : prix & devis`, description: `Regulation connectee pour ${t.taille} (${t.lots}). ${t.prix}. CEE. Audit gratuit.`, alternates: { canonical: url }, openGraph: { title: t.taille, description: `${t.prix}.`, locale: "fr_FR", type: "website", url, images: [{ url: t.image, width: 1200, height: 630, alt: t.taille }] }, robots: { index: true, follow: true } }; }
export default async function TaillePage({ params }: { params: Params }) { const { slug } = await params; const t = getThermoTailleBySlug(slug); const s = getCityBySlug("home") || Object.values(CITIES)[0]; if (!t || !s) return notFound(); const url = `${BASE}/taille/${slug}`; const intro = `<p class="mb-4">${t.description}</p><p>Budget : <strong>${t.prix}</strong> (${t.config}). Devis gratuit.</p>`; const secs = [{ title: `Solution ${t.taille}`, html: `<ul class="space-y-2">${t.points.map((p: string) => "<li>" + p + "</li>").join("")}</ul>` }]; return (<ThermoContentPage site={s} heroBadge="Solution copropriete" pageTitle={`Regulation connectee ${t.taille}`} introHtml={intro} facts={[{ label: "Lots", value: t.lots }, { label: "Budget", value: t.prix }, { label: "Solution", value: t.config }, { label: "CEE", value: "Oui" }]} benefits={t.points} expertTip={t.expertTip} faqs={[{ question: `Budget pour une ${t.taille} ?`, reponse: `Comptez ${t.prix} (${t.config}). Devis gratuit sous 24h.` }]} canonicalUrl={url} heroImage={t.image} breadcrumb={[{ name: t.taille, item: url }]} sections={secs} />); }