export const revalidate = 86400; // 24h ISR cache
import { getCityBySlug, CITIES } from "@/lib/db";
import { THERMO_TYPES, getThermoTypeBySlug } from "@/data/thermo-types";
import { notFound } from "next/navigation"; import type { Metadata } from "next";
import ThermoContentPage from "@/components/ThermoContentPage";
type Params = Promise<{ slug: string }>;
export async function generateStaticParams() { return THERMO_TYPES.map((t) => ({ slug: t.slug })); }
const BASE = "https://www.thermostatcopropriete.fr";
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const { slug } = await params; const t = getThermoTypeBySlug(slug); if (!t) return {}; const url = `${BASE}/type/${slug}`; return { title: `${t.name} : Prix & Devis | Thermostat Copropriete`, description: `${t.name} : ${t.prix}. ${t.aides}. Audit gratuit.`, alternates: { canonical: url }, openGraph: { title: t.name, description: `${t.prix}.`, locale: "fr_FR", type: "website", url, images: [{ url: t.image, width: 1200, height: 630, alt: t.name }] }, robots: { index: true, follow: true } }; }
export default async function TypePage({ params }: { params: Params }) { const { slug } = await params; const t = getThermoTypeBySlug(slug); const s = getCityBySlug("home") || Object.values(CITIES)[0]; if (!t || !s) return notFound(); const url = `${BASE}/type/${slug}`; const intro = `<p class="mb-4">${t.description}</p><p>Comptez <strong>${t.prix}</strong>. ${t.aides}. Audit gratuit.</p>`; const secs = [{ title: "Points cles", html: `<ul class="space-y-2">${t.points.map((p: string) => "<li>" + p + "</li>").join("")}</ul>` }, { title: "Ideal pour", html: `<p>${t.ideal}</p>` }]; return (<ThermoContentPage site={s} heroBadge="Solutions copropriete" pageTitle={t.name} introHtml={intro} facts={[{ label: "Prix", value: t.prix }, { label: "Duree", value: t.duree }, { label: "Aides", value: "CEE" }, { label: "Ideal", value: t.ideal.split(",")[0] }]} benefits={t.points} expertTip={t.expertTip} faqs={[{ question: `Quel est le prix de la ${t.shortName} ?`, reponse: `Comptez ${t.prix}. ${t.aides}.` }]} canonicalUrl={url} heroImage={t.image} breadcrumb={[{ name: t.name, item: url }]} sections={secs} />); }